jwt:
  secret:
    key: ${JWT_SECRET_KEY}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  cloud:
    gateway:
      routes:
        - id: user-server
          uri: http://couponmoa-dev-user-service:8081
          predicates:
            - Path=/api/v1/users/**, /api/v2/users/**, /api/v1/auth/**

#        - id: store-server
#          uri: http://couponmoa-dev-store-service:8082
#          predicates:
#            - Path=/api/v1/stores/**, /api/v2/stores/**
#
#        - id: coupon-server
#          uri: http://couponmoa-dev-coupon-service:8083
#          predicates:
#            - Path=/api/v1/coupons/**, /api/v2/coupons/**, /api/v1/user-coupons/**